package rexa

import (
	"errors"
	"strconv"
	"testing"
	"time"
)

// The platform ships a self-test in docs/integrations/call-agent-hmac-spec.md §6
// that both sides are expected to pass before integrating. Reproducing it here
// is the cheapest possible proof that our canonical string agrees with theirs;
// if this fails, nothing else in the contract can work.
func TestSpecSelfTest(t *testing.T) {
	const secret = "0000000000000000000000000000000000000000000000000000000000000000"
	body := []byte(`{"hello":"world"}`)

	env := Sign(secret, body)
	v := NewVerifier(secret, NewMemoryNonceStore())
	if err := v.Verify(body, env); err != nil {
		t.Fatalf("round-trip failed: %v", err)
	}

	// Tampered body must fail.
	v2 := NewVerifier(secret, NewMemoryNonceStore())
	if err := v2.Verify(append(body, '!'), env); !errors.Is(err, ErrSigMismatch) {
		t.Errorf("tampered body: got %v, want ErrSigMismatch", err)
	}

	// Wrong secret must fail.
	v3 := NewVerifier(secret+"ff", NewMemoryNonceStore())
	if err := v3.Verify(body, env); !errors.Is(err, ErrSigMismatch) {
		t.Errorf("wrong secret: got %v, want ErrSigMismatch", err)
	}
}

// Cross-implementation vector, generated by running the PLATFORM's own
// algorithm (packages/shared/src/utils/hmac.ts — `createHmac('sha256', secret)`
// over `${ts}\n${nonce}\n${body}`) under Node and pinning the output here.
//
// This is the test that actually matters. Everything else in this file proves
// we agree with ourselves; this proves we agree with them. Note the secret is
// 64 hex characters but is keyed as raw UTF-8 — Node's createHmac does not
// decode a string key, so neither may we, despite the platform naming the
// option `hmacSecretHex`.
func TestPlatformVector(t *testing.T) {
	const (
		secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
		ts     = "1700000000000"
		nonce  = "11111111-2222-3333-4444-555555555555"
		body   = `{"session_id":"a","tenant_id":"b"}`
		want   = "03ca38f072971348d005a459b144e8d85343c6747688e4e7fe923a98676099f8"
	)
	tsMs, err := strconv.ParseInt(ts, 10, 64)
	if err != nil {
		t.Fatal(err)
	}
	got := signAt(secret, []byte(body), time.UnixMilli(tsMs), nonce)
	if got.Signature != want {
		t.Fatalf("signature disagrees with the platform:\n got %s\nwant %s", got.Signature, want)
	}
	// And the same envelope must verify on the way back in. The vector's
	// timestamp is fixed in the past, so pin the verifier's clock to it —
	// otherwise this asserts the drift check, which is covered elsewhere.
	v := NewVerifier(secret, nil)
	v.now = func() time.Time { return time.UnixMilli(tsMs) }
	if err := v.Verify([]byte(body), got); err != nil {
		t.Errorf("platform vector failed our own verifier: %v", err)
	}
}

// The canonical string is "{ts}\n{nonce}\n{body}" with no trailing newline.
// Pinning it against a hand-computed vector guards against a refactor quietly
// changing the framing — which would still round-trip with ourselves and fail
// only against the platform.
func TestCanonicalFraming(t *testing.T) {
	got := string(canonical("1700000000000", "abc", []byte(`{"a":1}`)))
	want := "1700000000000\nabc\n{\"a\":1}"
	if got != want {
		t.Errorf("canonical =\n%q\nwant\n%q", got, want)
	}
}

// The secret is used as raw UTF-8, not hex-decoded, matching the platform's
// Python reference. Hex-decoding would produce signatures that look fine and
// never verify against the platform.
func TestSecretIsRawNotHexDecoded(t *testing.T) {
	const secret = "00ff"
	body := []byte("x")
	env := Sign(secret, body)
	// Verifying with the same literal string must pass...
	if err := NewVerifier(secret, nil).Verify(body, env); err != nil {
		t.Fatalf("raw-secret verify failed: %v", err)
	}
	// ...and with the hex-decoded bytes as the key, must not.
	if err := NewVerifier("\x00\xff", nil).Verify(body, env); !errors.Is(err, ErrSigMismatch) {
		t.Errorf("hex-decoded key verified; secret is being decoded somewhere")
	}
}

func TestMissingHeaders(t *testing.T) {
	v := NewVerifier("s", NewMemoryNonceStore())
	full := Sign("s", []byte("b"))
	for name, env := range map[string]Envelope{
		"no signature": {Timestamp: full.Timestamp, Nonce: full.Nonce},
		"no timestamp": {Signature: full.Signature, Nonce: full.Nonce},
		"no nonce":     {Signature: full.Signature, Timestamp: full.Timestamp},
	} {
		if err := v.Verify([]byte("b"), env); !errors.Is(err, ErrMissingHeaders) {
			t.Errorf("%s: got %v, want ErrMissingHeaders", name, err)
		}
	}
}

func TestBadTimestamp(t *testing.T) {
	env := Sign("s", []byte("b"))
	env.Timestamp = "not-a-number"
	if err := NewVerifier("s", nil).Verify([]byte("b"), env); !errors.Is(err, ErrBadTimestamp) {
		t.Errorf("got %v, want ErrBadTimestamp", err)
	}
}

// Drift is rejected in BOTH directions — clock skew is not one-sided, and a
// future-dated timestamp is as suspicious as a stale one.
func TestDriftRejectedBothDirections(t *testing.T) {
	body := []byte("b")
	for name, offset := range map[string]time.Duration{
		"stale":  -(MaxDrift + time.Minute),
		"future": MaxDrift + time.Minute,
	} {
		env := signAt("s", body, time.Now().Add(offset), "n-"+name)
		if err := NewVerifier("s", nil).Verify(body, env); !errors.Is(err, ErrDriftExceeded) {
			t.Errorf("%s: got %v, want ErrDriftExceeded", name, err)
		}
	}
	// Just inside the window must still pass.
	env := signAt("s", body, time.Now().Add(-(MaxDrift - time.Minute)), "n-ok")
	if err := NewVerifier("s", nil).Verify(body, env); err != nil {
		t.Errorf("within window: got %v, want nil", err)
	}
}

func TestNonceReplay(t *testing.T) {
	body := []byte("b")
	v := NewVerifier("s", NewMemoryNonceStore())
	env := Sign("s", body)
	if err := v.Verify(body, env); err != nil {
		t.Fatalf("first: %v", err)
	}
	if err := v.Verify(body, env); !errors.Is(err, ErrNonceReplay) {
		t.Errorf("second: got %v, want ErrNonceReplay", err)
	}
}

// A forged request must not be able to burn a nonce. If the replay check ran
// before signature verification, an attacker who observed a nonce could
// pre-register it and make the genuine request bounce.
func TestForgedRequestDoesNotConsumeNonce(t *testing.T) {
	body := []byte("b")
	store := NewMemoryNonceStore()
	v := NewVerifier("s", store)

	good := Sign("s", body)
	forged := Envelope{Signature: "deadbeef", Timestamp: good.Timestamp, Nonce: good.Nonce}
	if err := v.Verify(body, forged); !errors.Is(err, ErrSigMismatch) {
		t.Fatalf("forged: got %v, want ErrSigMismatch", err)
	}
	// The genuine request carrying that same nonce must still be accepted.
	if err := v.Verify(body, good); err != nil {
		t.Errorf("genuine after forged: got %v, want nil", err)
	}
}

// The platform reuses one nonce across its three dispatch retries so the
// receiver can collapse them. We must be able to do the same on callbacks.
func TestSignWithNonceIsStable(t *testing.T) {
	body := []byte("b")
	a := SignWithNonce("s", body, "fixed-nonce")
	b := SignWithNonce("s", body, "fixed-nonce")
	if a.Nonce != "fixed-nonce" || b.Nonce != "fixed-nonce" {
		t.Fatalf("nonce not preserved: %q %q", a.Nonce, b.Nonce)
	}
	// Signatures differ only because the timestamp moves; both must verify.
	v := NewVerifier("s", nil)
	if err := v.Verify(body, a); err != nil {
		t.Errorf("a: %v", err)
	}
	if err := v.Verify(body, b); err != nil {
		t.Errorf("b: %v", err)
	}
}

func TestNonceStoreEvictsExpired(t *testing.T) {
	s := NewMemoryNonceStore()
	base := time.Now()
	s.now = func() time.Time { return base }
	if s.SeenBefore("n") {
		t.Fatal("first call reported as seen")
	}
	// Past the TTL the entry is gone, so the same nonce is accepted again.
	s.now = func() time.Time { return base.Add(NonceTTL + time.Second) }
	if s.SeenBefore("n") {
		t.Error("nonce survived past NonceTTL")
	}
	if len(s.seen) != 1 {
		t.Errorf("expired entries not evicted: %d remain", len(s.seen))
	}
}

// Timestamps go on the wire in milliseconds. Seconds is the second pitfall the
// platform's spec calls out by name.
func TestTimestampIsMilliseconds(t *testing.T) {
	env := Sign("s", []byte("b"))
	ms, err := strconv.ParseInt(env.Timestamp, 10, 64)
	if err != nil {
		t.Fatalf("timestamp not an integer: %v", err)
	}
	delta := time.Since(time.UnixMilli(ms))
	if delta < 0 {
		delta = -delta
	}
	if delta > time.Minute {
		t.Errorf("timestamp %d is not epoch-ms (off by %v)", ms, delta)
	}
}
